# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcbb29e5b6e949a2c35a2a1711cc75323047881c8f6baca5d3c53fd1c928c8754ad04d8baff0d4753bc1d71563ba699ebe340b13fc21658a1442c7b7a44f5f2

test:
  secret_key_base: 1e3356af074aee8fb05479eaf032d62db77ddfec004f1308fc005e7479462f0a9d1d831831cecc81bbbb5fc56b2c84b47feaf5d38ce02f5b48ee220ad2c7697a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
